name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag anthonykgross/ansible-vault-cli-github-action:latest
    - name: Create encrypted file
      run: bash tests/tests.sh

    - run: echo 'fake confidential data' > foo.yml
    - name: Test the action
      uses: ./
      with:
        vault_key: '1234'
        args: "ansible-vault encrypt foo.yml"
    - run: cat foo.yml
